export const projectData = [
  {
    id: 1,
    name: "Amazon Clone",
    tags: ["nextJs", "Tailwind CSS", "Redux"],
    link: "https://amazon-clone-nextjs-rahulsomu.vercel.app/",
    image: "https://i.postimg.cc/tJbSxcnn/amazon.png",
    featured: true,
    description:
      "An amazon clone built using Next Js with google sign in option.Redux is used for state management",
  },

  {
    id: 2,
    name: "Tesla Clone",
    tags: ["React", "material UI"],
    link: "https://rahulsomu.github.io/tesla/",
    image: "https://i.postimg.cc/4y18b1pL/tesla.png",
    featured: true,
    description: "A Tesla clone built using React Js amd styled components.",
  },
  {
    id: 3,
    name: "Dictionary",
    tags: ["React", "material UI"],
    link: "https://my-dictionaryy.netlify.app/",
    image: "https://i.postimg.cc/1tw74SXZ/dictionary.png",
    featured: true,
    description:
      "A dictionary app which can be used to search the meaning of anything you need to know.It also has an audio feature which can pronounce the word.",
  },
  {
    id: 4,
    name: "Instagram Clone",
    tags: ["React", "material UI"],
    link: "https://instagram-rahul.herokuapp.com/",
    image: "./instagram.png",
    featured: false,
  },
  {
    id: 5,
    name: "Vanilla JS Calculator",
    tags: ["HTML", "CSS", "Javascript"],
    link: "https://rahulsomu.github.io/Vanilla-javascript-Calculator/",
    image: "./calculator.png",
    featured: false,
  },
  {
    id: 6,
    name: "Amazon Prime",
    tags: ["React", "Material UI"],
    link: "https://rahul-amazon-prime.netlify.app/",
    image: "./amazon-prime.png",
    featured: false,
  },
  {
    id: 7,
    name: "Animated Hamburger Menu",
    tags: ["Css", "Html"],
    link: "https://rahulsomu.github.io/hamburger/",
    image: "https://i.postimg.cc/FK2n9z9Z/burger.png",
    featured: true,
    description:
      "An amazing CSS only hover effect.Hover on the hamburger to see the magic!.",
  },
  {
    id: 8,
    name: "Covid Tracker",
    tags: ["React", "Material UI"],
    link: "https://rahulsomu.github.io/covid-cases/",
    image: "./covid.png",
    featured: false,
  },
  {
    id: 9,
    name: "To-Do app",
    tags: ["Javascript", "CSS", "HTML"],
    link: "https://rahulsomu.github.io/Todo/",
    image: "./todo.png",
    featured: false,
  },
  {
    id: 10,
    name: "Temperature Converter",
    tags: ["Javascript", "CSS", "HTML"],
    link: "https://rahulsomu.github.io/temperature-converter/",
    image: "./temperature.png",
    featured: false,
  },
  {
    id: 11,
    name: "Random Color Generator ",
    tags: ["Javascript", "CSS", "HTML"],
    link: "https://rahulsomu.github.io/Random-color-changer/",
    image: "./color.png",
    featured: false,
  },
  {
    id: 12,
    name: "Emoji Search ",
    tags: ["Javascript", "CSS", "HTML", "React JS"],
    link: "https://find-emo.netlify.app/",
    image: "https://i.postimg.cc/k5Vp3KdG/emoji.png",
    featured: true,
    description:
      "An app to search your favourite emojis.You can also copy the emoji by clicking on it.",
  },
  {
    id: 13,
    name: "CSS only Lamborghini",
    tags: ["Javascript", "CSS", "HTML"],
    link: "https://rahulsomu.github.io/css-only-lamborghini/",
    image: "https://i.postimg.cc/rwZPPg37/lambo.png",
    featured: true,
    description:
      "An amazing CSS only hover effect Hover on the box to see the magic!.",
  },
];
